### ISSUE TITLE
change http:// mozilla resources to https://

### ISSUE THREAD

**Issue by Pomax** [chadsansing/curriculum-testing#120]
As the github.io page runs on `https://`, resources that it relies on from `http://` will not load due to "insecure content" rules in most current browsers. Just swapping the `http://` for `https://` on mozilla resources should fix that

**Comment by chadsansing** [comment]
Hit the web-lit-basics-two, expanded-privacy-curriculum, & moz-fest-remote-projects repos. Thanks, @pomax!
