### ISSUE TITLE
CSS Circles

### ISSUE THREAD

**Issue by jgmac1106** [chadsansing/curriculum-testing#202]
I like the tutorial. A good start. You may want to add a tip about hitting Command/Control-E on the color codes to bring up the color selectors.

**Comment by chadsansing** [comment]
I saw that in the six-word story template. Me gusta. Will likely add it along with reminder to practice reading the stylesheet, as well. Thinking of float next.

**Comment by jgmac1106** [comment]
I can't wait. The intermediate web design kit if it can handle positioning
in CSS we will be off to a great start. I was wondering about responsive
text design but was thinking that might fit as its own teaching kit all
together..but could fit intermediate design as well.

I know this isn't the issue but is there a discourse thread or MLN thread
about Intermediate?

**Comment by chadsansing** [comment]
Not yet; waiting for Orlando and Q1 to trigger before making the next round of asks for feedback and testing. This may be more P2 than P1. Scoping and prototyping while I have the time.
