### ISSUE TITLE
[Event planning] Gather documentation from project meet-up

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/curriculum-testing#381]
## Documentation plan for meet-ups

- [ ] Take photos and video in the commons area. Be mindful of people who opt out of recording! **@assignee**
- [ ] Video interview five participants in the commons area. Be mindful of people who opt out of recording! **@assignee**
- [ ] Set up, run, and tear down video recording equipment for speakers' presentations.**@assignee**
- [ ] Monitor and collect social media posts mentioning the event and create a [Storify](https://storify.com/). **@assignee**
- [ ] Invite speakers to share their slide-decks for event reporting.**@assignee**
- [ ] Gather and curate blog posts written by attendees and presenters during and after the event. **@assignee**

**Comment by jgmac1106** [comment]
I also think we should connect with virtually connecting
<http://virtuallyconnecting.org/> to support our remote efforts. I have
been both an on the ground and virtual buddy. What Maha and and Rebecca
built is a perfect fit for Mozilla Meet ups.

Might add write summary blog posts and syndicate to Mozilla Learning blogs
and Medium.

**Comment by chadsansing** [comment]
Nice - by the by, take this issue with a grain of salt - it's a mock-up example for a screen-shot elsewhere :)

**Comment by jgmac1106** [comment]
Oops didn't even see it was in your personal repo.
