### ISSUE TITLE
DSO Intervention 1: Links in headers don't work

### ISSUE THREAD

**Issue by secretrobotron** [chadsansing/curriculum-testing#398]
The links at the top of each page in the DSO Intervention 1 curriculum don't work.

`Smartphone Basics For the Kenya DSO Project` -> 404
`Intervention One: The Smartphone Ecosystem` -> Nothing (but webpage hash changes)

<img width="814" alt="screenshot 2016-06-01 11 25 43" src="https://cloud.githubusercontent.com/assets/403231/15704581/a47ca5f2-27eb-11e6-84a9-1436ef42f446.png">

**Comment by chadsansing** [comment]
The first one will work if we develop a landing page/index. I can nerf it for now. The second one I'll fix -

**Comment by chadsansing** [comment]
Fixed in #399.
