### ISSUE TITLE
Skills should be listed the same way

### ISSUE THREAD

**Issue by secretrobotron** [chadsansing/curriculum-testing#400]
21st century skills and Web Literacy skills lists should look the same:
 
![screenshot 2016-06-01 14 56 09](https://cloud.githubusercontent.com/assets/403231/15710161/00a85fe8-2809-11e6-9e63-5210b38885d1.png)

**Comment by chadsansing** [comment]
@flukeout, can we experiment with a similar treatment for both the 21st C Skills and web literacy skills? @hannahkane might be able to ship you colors for the blocks, as well, based on badge work done with DigitalMe.

**Comment by hannahkane** [comment]
We could do a stop-gap measure here for consistency, but I think the real fix for this likely comes when we get to the curriculum database project. This will be structured data, so the skills will serve as navigational elements.

**Comment by LauraReynal** [comment]
+1 on listing the skills the same way

**Comment by chadsansing** [comment]
Maybe I can just hack a fix with some copy-paste.

**Comment by chadsansing** [comment]
Hacked.
