### ISSUE TITLE
Change "the Net" to "the internet" in Intervention 1

### ISSUE THREAD

**Issue by secretrobotron** [chadsansing/curriculum-testing#401]
At the end of the introductions section, the internet is referred to as "the Net". It should probably be "the internet".

![screenshot 2016-06-01 17 56 20](https://cloud.githubusercontent.com/assets/403231/15716358/405633c2-2822-11e6-9f2d-a308bfdc35de.png)

**Comment by chadsansing** [comment]
Fixed.
