### ISSUE TITLE
Curriculum 1 - Copy edit for the overview 

### ISSUE THREAD

**Issue by LauraReynal** [chadsansing/curriculum-testing#427]
Curriculum 1 - Overview http://chadsansing.github.io/curriculum-testing/kenya-dso-interventions/01-intervention-one.html#overview 

The **overview** section should have an intro about DSO and the hypothesis we were testing for this piece of curriculum. 

suggestions, please edit as you see fit @secretrobotoron @chadsansing 

**The Digital Skills Observatory**
This curriculum was created as part of the [Digital Skills Observatory](mzl.la/dso) research project. It is the first of the 6 interventions that aims to study the impact of digital skills training modules, on the way that new smartphone users adopt and use their phone, mobile applications and the web.

Testing various teaching and delivery methods, the study aims to understand the skills people need to develop confidence and agency with their smartphones, and to use digital financial services (DFS).

The learners concerned by this study are completely new to the web, apps, and smartphones. They live in difficult conditions, with less than 5 USD per day. 

**Running this workshop**
As part of this experimental research project, this workshop was co-created and facilitated by a community of volunteers and researchers in Kenya. 

**Measuring impact**
Because this curriculum is an intervention in our treatment group, we are very focus on data collection and take time to analyse learnings and observations from these workshops.

**Comment by LauraReynal** [comment]
Is this copy too long ?

**Comment by LauraReynal** [comment]
These links could be added somewhere as well 
https://mozilla-foundation-research.herokuapp.com/dso-kisumu-first-intervention/

https://mozilla-foundation-research.herokuapp.com/tamasha-hack/ 

https://mozilla-foundation-research.herokuapp.com/dso-nairobis-first-intervention/

**Comment by chadsansing** [comment]
@LauraReynal, typically, when a module goes up on /learning, there's a landing page that links out to individual lessons. I think that page might be the better place for project overview. Conventionally, none of the other modules has an introduction to its larger project inside any lesson.

Does that make sense? The time to make that page and post that copy is typically when we ship a module to @hannahkane on a content document [like this one](https://docs.google.com/a/mozilla.com/document/d/1oNXBYCgZw0AJbiK_FGYTDRVpqMBz0UiPi0yCCYbYdSc/edit?usp=sharing) that holds the meta info.

Or we could make a project page or use an existing one to hold this info and link to the interventions. What do you think?

cc @secretrobotron

**Comment by LauraReynal** [comment]
ahh ok I get it. I just wanted to give a bit of context because we use language like "DSO" in the title.

**Comment by LauraReynal** [comment]
Maybe we can reduce my copy to a couple of sentences, and add it in the overview ?
@secretrobotron what do you think ?

**Comment by chadsansing** [comment]
@LauraReynal, @secretrobotron - do we want copy on the activity pages themselves, or on the typical module index/content page that appears off of /activities?
