### ISSUE TITLE
Curriculum 1 - edit title 

### ISSUE THREAD

**Issue by LauraReynal** [chadsansing/curriculum-testing#430]
@chadsansing @secretrobotron

I propose to change the title from **_"Smartphone Basics For the Kenya DSO Project | Intervention One: The Smartphone Ecosystem"_** to something wider such as : 

Digital Skills Observatory | Intervention One: The Smartphone Ecosystem

It helps us keep clarity in the content architecture linked to #429

**Comment by chadsansing** [comment]
Updated.
