### ISSUE TITLE
Curriculum 1 - Preparation 

### ISSUE THREAD

**Issue by LauraReynal** [chadsansing/curriculum-testing#431]
The last paragraph seems disconnected from this audience who is not using the web literacy map. It is full of concepts that we are not ready to use yet. 

https://www.dropbox.com/s/qjbjbb5eh2fedqp/Screenshot%202016-07-26%2012.16.44.png?dl=0

What do you think @chadsansing @secretrobotron ?

**Comment by LauraReynal** [comment]
@chadsansing we can add these couple of pictures to illustrate this page 

https://www.flickr.com/photos/laura_nk/26642091971/in/album-72157663345939379/

and / or 

https://www.flickr.com/photos/laura_nk/26642089341/in/album-72157663345939379/

**Comment by chadsansing** [comment]
Commented out for now, though I would rather we encourage the facilitators to look at the map since web literacy is a key issue and the map is our vehicle for it. The idea here is for facilitators to prepare by looking at the map. Maybe we could structure the language a bit more to ask that facilitators think about how their work connects to it?

Images added.

**Comment by LauraReynal** [comment]
Or update the map with the other skills or other language?

**Comment by chadsansing** [comment]
I doubt that we're ready to revise the map so early in its 2.0 life-cycle. I think skills like Connect, Evaluate, Navigate, Protect, and Search relate clearly and directly to what facilitators teach in this curriculum. I'd have no problem asking them to check out the map and think about how our work and theirs are related here, but defer to DA out of DARCI.

**Comment by LauraReynal** [comment]
Ok that's awesome. It's worth talking about this next time, because sometimes, it feels like we are teaching Android Technical Skills, that are less directly related to the web and to the web lit map. 
what do you think ? 
cc @secretrobotron

**Comment by LauraReynal** [comment]
I like your idea of sharing the map with the facilitators and asking them what they think

**Comment by chadsansing** [comment]
@LauraReynal - but these android devices *are* how this audience experiences the web.

**Comment by LauraReynal** [comment]
True. So where do they fit in the web lit map ? 
Read?

**Comment by chadsansing** [comment]
Some are participate:

![screen shot 2016-07-26 at 12 41 00 pm](https://cloud.githubusercontent.com/assets/4128600/17146902/412a9a5e-532e-11e6-924a-fafbd9fa319c.png)

Some are read:

![screen shot 2016-07-26 at 12 41 07 pm](https://cloud.githubusercontent.com/assets/4128600/17146909/46dbfe34-532e-11e6-831f-58b889a0f47f.png)
