### ISSUE TITLE
Layout - all of the boxes are of the same color

### ISSUE THREAD

**Issue by lauradereynal** [chadsansing/curriculum-testing#434]
All of the boxes of colors are the same pink / red, which is confusing because it mixes different levels of information such as faciliator tips, and actual content of spectrograms or explanations. 

https://www.dropbox.com/s/dgix07aqi5pj1qq/Screenshot%202016-07-26%2012.24.15.png?dl=0

@chadsansing Can we make all the facilitator tips the same color, and all the content another color  ?

**Comment by chadsansing** [comment]
@LauraReynal - I'll see what I can hack, but not per se. We're using the curriculum template stylesheet. We can ask @flukeout if there's not an immediate fix I can find.

**Comment by chadsansing** [comment]
@LauraReynal - what counts as a tip or as content? Are the questions facilitators ask tips for them or content?

**Comment by chadsansing** [comment]
You can see possible changes [here](http://chadsansing.github.io/curriculum-testing/kenya-dso-interventions/01-intervention-one.html) now.

**Comment by LauraReynal** [comment]
@chadsansing the tips are things like : "prepare this" or "a spectogram is this" 
and content is more : "the internet is cool, it has multiple pages..."

makes sense ? 

Awesome for the changes thanks !

**Comment by chadsansing** [comment]
I think my specific uncertainty is around lists of questions. Are these suggestions/tips for the facilitator to use or part of the content of the lesson? If they are content, then we will have a ton of the new color, and just a bit of the old color.

**Comment by LauraReynal** [comment]
I think they are content more than tips, but I see how that's just uncertain. 
I'll let you have the final word and decision

**Comment by flukeout** [comment]
So what I'm hearing is that we would like a different styling for content that is aimed at the faciliator, with ideas and prompts for making the activity go smoother, right? It's thing they're meant to think about or do, that aren't part of the actual content.

In that case, I think a kind of post-it yellow styling might be appropriate. If you'd like I can take a crack at that @chadsansing

**Comment by flukeout** [comment]
We could also put a little title on these boxes like "Tips" or "Suggestions" - open to ideas.

**Comment by chadsansing** [comment]
I made a light blue stop-gap measure, but the sticky-note-yellow connection is nice.

**Comment by chadsansing** [comment]
@flukeout, @LauraReynal - anything new here, or can we close?

**Comment by flukeout** [comment]
Nothing new yet - but tackling today.
