### ISSUE TITLE
Curriculum 1 - how do smartphone work: add an overview 

### ISSUE THREAD

**Issue by LauraReynal** [chadsansing/curriculum-testing#435]
http://chadsansing.github.io/curriculum-testing/kenya-dso-interventions/01-intervention-one.html#step-3

In the section 3, we cover 4  main substantial topics: 
- Smartphone usage 
- Smartphones can connect to the cellular network
- Smartphones can connect to the internet 
- Smartphones can use airtime and mobile data 

Would it be possible to outline them at the top of the page to have more clarity? 
How about numbering them as well ? 

Thoughts @chadsansing @secretrobotron ?

**Comment by chadsansing** [comment]
Updated.
