### ISSUE TITLE
Curriculum 1 - What is the internet ?

### ISSUE THREAD

**Issue by LauraReynal** [chadsansing/curriculum-testing#436]
The first sentence "Facilitate a discussion..." should be outside of the pink box which contains prompts
https://www.dropbox.com/s/iucp21c70vds8fv/Screenshot%202016-07-26%2012.29.37.png?dl=0

@chadsansing

**Comment by LauraReynal** [comment]
some photos we can add here 

https://www.flickr.com/photos/laura_nk/15717291089/in/album-72157647756136177/
and 

https://www.flickr.com/photos/laura_nk/26104278733/in/album-72157663345939379/

**Comment by chadsansing** [comment]
Updated and added.
