### ISSUE TITLE
Migrate final curriculum to new repo

### ISSUE THREAD

**Issue by flukeout** [chadsansing/curriculum-testing#478]
As discussed with @chadsansing it's time to move some of the curriculum from this repo into a new one within the mozilla organization.

* Should we just call the new repo ``curriculum``?

**Final Curriculum**
* All activities in ``color-picker-challange``
* All activities in ``/curriculum migration`` folder
* All activities in ``/encryption`` folder
* All activities in ``/intermediate-web-lit-two`` folder
* All activities in ``/kenya-dso-interventions-folder``
* All activities in ``/offline-icebreakers``
* All activities in ``/what-if-they-had-the-web``
* All activities in ``/updated-web-lit-basics``

**Also To-Do**
* Add favicon
* Make sure all of the activities are using the same CSS and JS
* Template styling https://github.com/mozilla/learning.mozilla.org/issues/2028
* Next activity button https://github.com/mozilla/learning.mozilla.org/issues/1655
* License https://github.com/mozilla/learning.mozilla.org/issues/1654
* Layout color https://github.com/chadsansing/curriculum-testing/issues/434
* Create an updated README.md 
  * We can include links to all of the curriculum on this
* Remove dependency on Font Awesome
  * We only use a couple of icons, so I'll convert them to SVGs

Once this is done, we'll need to update any links we have on our sites to point to the new curriculum. Or maybe we could just wait until the new curriculum DB stuff is working and update it there.

@chadsansing - anything to add to this?

**Comment by chadsansing** [comment]
@flukeout:

Yes - `curriculum` works.

This sounds right; so excited for the project! 

We should create some time at the next all-hands for @mmmavis, @hannahkane, and us to get my machine and brain ready to help more with PRs, etc.

**Comment by flukeout** [comment]
@chadsansing There is already a ``curriculum`` repo on the mozilla org - https://github.com/mozilla/curriculum. 

I'm worried that people might already be linking to stuff inside there, do you know if that's the case? Maybe for now I'll set up a ``curriculum-final`` repo. We can rename it later anyway.

**Comment by chadsansing** [comment]
Okay - also ask @ldecoursey about the pre-existing repo?

**Comment by hannahkane** [comment]
+1 to waiting for curriculum db, rather than change all links.

I think we're looking for feedback from @ldecoursy.

**Comment by chadsansing** [comment]
@ldecoursy doesn't think anything I've made has wound up anywhere else yet, so we can move ahead, I think.

**Comment by flukeout** [comment]
Thanks @chadsansing

**Comment by flukeout** [comment]
Okay so this is done! Currently it's hanging out in github.com/mozilla/curriculum-final until we retire the ``curriculum`` repo.

Let's file issues in that repo, things still need a bit of cleanup.
